/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version, build and feature flags (e.g. SRT availability) */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hardware self-check and recommended local model sizes (AI-12) */
        get: operations["getHardwareReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the local provider on a bundled clip and report real-time factor (AI-12) */
        post: operations["runBenchmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supported source and target languages */
        get: operations["listLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** First-run setup status */
        get: operations["getSetupStatus"];
        put?: never;
        /** Set the admin PIN on first run (only allowed while no PIN exists) */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current auth state */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions (admin view) */
        get: operations["listSessions"];
        put?: never;
        /** Create session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Get session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Delete session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        /** Update session */
        patch: operations["updateSession"];
        trace?: never;
    };
    "/api/sessions/{sessionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start session */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause session */
        post: operations["pauseSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop session */
        post: operations["stopSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Live status snapshot (the dashboard also receives it via /ws/admin) */
        get: operations["getSessionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/ingest-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the per-session ingest token (invalidates the previous one) */
        post: operations["rotateIngestToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/sources/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feed a local file or URL at real-time speed as the session's audio (AUD-3, dev/test) */
        post: operations["startFileSource"];
        /** Stop file source */
        delete: operations["stopFileSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/stream-captions/youtube-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Set the YouTube caption ingestion URL (write-only secret) (CC-1, CC-2) */
        put: operations["putYoutubeCaptionUrl"];
        post?: never;
        /** Remove the YouTube caption ingestion URL */
        delete: operations["deleteYoutubeCaptionUrl"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/stream-captions/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test caption to the configured stream-caption target (CC-3) */
        post: operations["sendTestStreamCaption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions visible to the audience (no tokens, no config) */
        get: operations["listPublicSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Get public session */
        get: operations["getPublicSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/sessions/{sessionId}/captions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Final captions history (JSON, paginated) */
        get: operations["listCaptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/sessions/{sessionId}/subtitles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Subtitle file (live or export) in VTT, SRT, TXT or JSON (OUT-6, OUT-7, OUT-8)
         * @description With `live=true` the response contains all final cues so far and is
         *     served with `Cache-Control: no-store`, so players and tools can poll it.
         *     Without `live`, `Content-Disposition: attachment` is set.
         */
        get: operations["getSubtitles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/captions/{segmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
                segmentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Live correction, edit or hide a caption line (ADM-4) */
        patch: operations["patchCaption"];
        trace?: never;
    };
    "/ws/ingest/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Audio ingest WebSocket (AUD-1)
         * @description 1. Client sends an `IngestHello` text frame.
         *     2. Server replies with `IngestServerMessage{type: ready}`.
         *     3. Client sends **binary** frames of raw PCM, `s16le`, 16 kHz, mono,
         *        20–100 ms each.
         *     4. Server periodically sends `IngestServerMessage{type: level}` and
         *        `state`/`error` messages.
         *     Only one ingest connection per session is active; a new one replaces the old
         *     (`error.code = ingest.replaced` is sent to the old one).
         */
        get: operations["wsIngest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/captions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Live caption stream for one session (OUT-1)
         * @description Server → client JSON text frames of type `CaptionsServerMessage`.
         *     On connect the server sends `history` (recent final captions) and then
         *     live `caption` events. Pass `lang` several times to subscribe to more than
         *     one track (e.g. stage screen dual-language); `lang=source` is the
         *     original-language track.
         */
        get: operations["wsCaptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin event stream (session status, levels, latency, errors) (ADM-1)
         * @description Server → client JSON text frames of type `AdminEvent`.
         */
        get: operations["wsAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get settings */
        get: operations["getSettings"];
        /** Update settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider availability and the resolved default (AI-4, AI-11) */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Known secrets with masked hints only; values are never returned (SEC-1) */
        get: operations["listSecrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        get?: never;
        /** Write-only; stores in OS keychain or encrypted file (SEC-2, SEC-3) */
        put: operations["putSecret"];
        post?: never;
        /**
         * Delete secret
         * @description A secret provided by an environment variable can't be deleted here (409 `secret.read_only_env`).
         */
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets/{name}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check the stored secret against its service (e.g. Gemini API key) (SEC-5) */
        post: operations["validateSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List glossaries */
        get: operations["listGlossaries"];
        put?: never;
        /** Create glossary */
        post: operations["createGlossary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossaries/{glossaryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glossaryId: string;
            };
            cookie?: never;
        };
        /** Get glossary */
        get: operations["getGlossary"];
        /** Update glossary */
        put: operations["updateGlossary"];
        post?: never;
        /** Delete glossary */
        delete: operations["deleteGlossary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlay-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public, the overlay page loads its preset without auth */
        get: operations["listOverlayPresets"];
        put?: never;
        /** Create overlay preset */
        post: operations["createOverlayPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlay-presets/{presetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: string;
            };
            cookie?: never;
        };
        /** Get overlay preset */
        get: operations["getOverlayPreset"];
        /** Update overlay preset */
        put: operations["updateOverlayPreset"];
        post?: never;
        /** Delete overlay preset */
        delete: operations["deleteOverlayPreset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LAN addresses and the base URL used for QR codes (OUT-4) */
        get: operations["getNetworkInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recordings */
        get: operations["listRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk usage of recordings (REC-5) */
        get: operations["getRecordingUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        /** Get recording */
        get: operations["getRecording"];
        put?: never;
        post?: never;
        /** Delete recording */
        delete: operations["deleteRecording"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recordingId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        /** Recorded audio (AAC in fragmented MP4); supports HTTP Range (REC-2) */
        get: operations["getRecordingAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recordingId}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-transcribe/translate a recording offline (REC-6, stretch) */
        post: operations["reprocessRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local models (whisper, Gemma) and their download status (AI-13) */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{modelId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start (or resume) a model download; progress is polled via GET /api/models and pushed on /ws/admin */
        post: operations["downloadModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get TLS info */
        get: operations["getTlsInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tls/ca.crt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local CA certificate to install on LAN devices (TLS-4) */
        get: operations["downloadCaCert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example main-stage */
        Slug: string;
        /**
         * @description ISO 639-1 code
         * @example es
         */
        LanguageCode: string;
        /**
         * @description `auto` detects between English and Spanish per segment (AI-10)
         * @default auto
         * @enum {string}
         */
        SourceLanguage: "auto" | "en" | "es";
        /**
         * @description `mock` is dev-only (scripted captions)
         * @enum {string}
         */
        ProviderKind: "gemini" | "local" | "mock";
        /**
         * @description `default` resolves via the default-provider rule (AI-11)
         * @default default
         * @enum {string}
         */
        ProviderChoice: "default" | "gemini" | "local" | "mock";
        /** @enum {string} */
        SessionState: "idle" | "starting" | "live" | "paused" | "stopping" | "error";
        /** @enum {string} */
        AudioSourceKind: "browser" | "file" | "srt" | "device";
        /** @enum {string} */
        SubtitleFormat: "vtt" | "srt" | "txt" | "json";
        /**
         * @description Known secret names; extended as providers are added
         * @enum {string}
         */
        SecretName: "google_api_key" | "obs_websocket_password";
        /**
         * Format: date-time
         * @example 2026-09-25T13:30:00Z
         */
        Timestamp: string;
        Error: {
            /**
             * @description Stable, translatable error code (UI-4)
             * @example session.not_found
             */
            code: string;
            /** @description English fallback text */
            message: string;
            /** @description Interpolation values for the translated message */
            params?: {
                [key: string]: unknown;
            };
            /** @description Per-field error codes for form validation */
            fields?: {
                [key: string]: string;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks?: {
                [key: string]: string;
            };
        };
        SystemInfo: {
            /** @example 0.1.0 */
            version: string;
            /** @example 22f9237 */
            commit?: string;
            /**
             * @example edge
             * @enum {string}
             */
            mode: "dev" | "edge" | "cloud";
            features: {
                /** @description ffmpeg with libsrt detected */
                srtIngest: boolean;
                /** @description ffmpeg available */
                recording: boolean;
                tls: boolean;
            };
        };
        Language: {
            code: components["schemas"]["LanguageCode"];
            /** @example Spanish */
            name: string;
            /** @example Español */
            nativeName: string;
            canBeSource: boolean;
        };
        HardwareReport: {
            os: string;
            arch: string;
            cpu: {
                model: string;
                cores: number;
            };
            /** Format: int64 */
            memoryBytes: number;
            gpus: {
                name: string;
                /** @enum {string} */
                backend: "metal" | "cuda" | "vulkan" | "none";
                /** Format: int64 */
                memoryBytes?: number;
            }[];
            runtimes: {
                whisper: components["schemas"]["RuntimeStatus"];
                ollama: components["schemas"]["RuntimeStatus"];
                ffmpeg: components["schemas"]["RuntimeStatus"];
            };
            recommendation: {
                /** @example large-v3-turbo */
                whisperModel: string;
                /** @example gemma3:4b */
                gemmaModel: string;
                localRealtimeLikely: boolean;
            };
            lastBenchmark?: components["schemas"]["BenchmarkResult"];
        };
        RuntimeStatus: {
            reachable: boolean;
            version?: string;
            url?: string;
            detail?: string;
        };
        BenchmarkResult: {
            /** @description Processing time / audio duration; < 1 means faster than real time */
            realTimeFactor: number;
            asrMs: number;
            translationMs: number;
            ok: boolean;
            ranAt: components["schemas"]["Timestamp"];
        };
        SetupStatus: {
            completed: boolean;
            adminPinSet: boolean;
            googleApiKeySet: boolean;
            localModelsReady: boolean;
        };
        SetupRequest: {
            pin: string;
        };
        LoginRequest: {
            pin: string;
        };
        Me: {
            authenticated: boolean;
        };
        SessionBase: {
            /** @example Main stage */
            name?: string;
            /** @example Sala Konex */
            room?: string;
            sourceLanguage?: components["schemas"]["SourceLanguage"];
            /** @description Defaults to settings.defaultTargetLanguages (`[es, en]`) */
            targetLanguages?: components["schemas"]["LanguageCode"][];
            provider?: components["schemas"]["ProviderChoice"];
            glossaryId?: string | null;
            /** @description Defaults to settings.recording.enabledByDefault */
            recordingEnabled?: boolean;
            stageStyle?: components["schemas"]["StageStyle"];
            streamCaptions?: components["schemas"]["StreamCaptionsConfig"];
        };
        SessionCreate: components["schemas"]["SessionBase"] & {
            slug: components["schemas"]["Slug"];
        };
        SessionUpdate: components["schemas"]["SessionBase"];
        Session: components["schemas"]["SessionBase"] & {
            id: components["schemas"]["Slug"];
            effectiveProvider: components["schemas"]["ProviderKind"];
            state: components["schemas"]["SessionState"];
            urls: components["schemas"]["SessionUrls"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        SessionWithToken: components["schemas"]["Session"] & {
            /** @example 3q9Zx7kT0bW5nR2mYp8vLc */
            ingestToken: string;
        };
        IngestToken: {
            /** @example 3q9Zx7kT0bW5nR2mYp8vLc */
            ingestToken: string;
        };
        /** @description Absolute URLs built from NetworkInfo.viewerBaseUrl */
        SessionUrls: {
            /** @example http://192.168.1.20:8080/s/main-stage */
            viewer: string;
            /** @example http://192.168.1.20:8080/stage/main-stage */
            stage: string;
            /** @example http://192.168.1.20:8080/overlay/main-stage?lang=en */
            overlay: string;
            /**
             * @description Without token; the admin UI appends it
             * @example http://192.168.1.20:8080/capture/main-stage
             */
            capture: string;
            /** @example http://192.168.1.20:8080/replay/main-stage */
            replay: string;
            /** @example srt://192.168.1.20:9000?streamid=main-stage */
            srtIngest?: string | null;
        };
        StageStyle: {
            /**
             * @default white-on-black
             * @enum {string}
             */
            preset: "white-on-black" | "yellow-on-black" | "black-on-white";
            /** @default false */
            dualLanguage: boolean;
            /** @default true */
            showQr: boolean;
            /** @default 3 */
            lines: number;
        };
        SessionStartRequest: {
            source?: components["schemas"]["AudioSourceKind"];
        };
        FileSourceRequest: {
            /** @description Local path under the data/testdata dir, or http(s) URL */
            uri: string;
            /** @default false */
            loop: boolean;
            /** @default 0 */
            startAtSec: number;
        };
        PublicSession: {
            id: components["schemas"]["Slug"];
            /** @example Main stage */
            name: string;
            /** @example Sala Konex */
            room?: string;
            state: components["schemas"]["SessionState"];
            detectedLanguage?: components["schemas"]["LanguageCode"];
            /**
             * @description Available caption tracks (target languages; `source` is always available)
             * @example [
             *       "es",
             *       "en"
             *     ]
             */
            languages: components["schemas"]["LanguageCode"][];
            /** @description Show the "this session is recorded" notice (REC-5) */
            recording?: boolean;
            stageStyle?: components["schemas"]["StageStyle"];
        };
        SessionStatus: {
            sessionId: components["schemas"]["Slug"];
            state: components["schemas"]["SessionState"];
            provider?: components["schemas"]["ProviderKind"];
            startedAt?: components["schemas"]["Timestamp"];
            detectedLanguage?: components["schemas"]["LanguageCode"];
            audio?: components["schemas"]["AudioStatus"];
            /** @description Per caption track (`source` + target languages) */
            latency?: {
                [key: string]: components["schemas"]["LatencyStats"];
            };
            usage?: components["schemas"]["UsageStats"];
            /** @example 142 */
            viewers: number;
            /** @example rec-main-stage-20260925-133000 */
            recordingId?: string | null;
            srt?: components["schemas"]["SrtStats"];
            streamCaptions?: components["schemas"]["StreamCaptionStatus"];
            error?: components["schemas"]["Error"];
        };
        AudioStatus: {
            connected: boolean;
            source?: components["schemas"]["AudioSourceKind"];
            /**
             * @description RMS over the last window
             * @example -18.5
             */
            levelDbfs?: number;
            /** @example -6.2 */
            peakDbfs?: number;
            silent?: boolean;
            clipping?: boolean;
            /** @description Duration of the last reconnect gap (SES-5) */
            lastGapMs?: number;
        };
        LatencyStats: {
            /** @example 1800 */
            p50Ms: number;
            /** @example 3100 */
            p95Ms: number;
            /** @example 1650 */
            lastMs?: number;
        };
        UsageStats: {
            audioSeconds?: number;
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            estimatedCostUsd?: number;
        };
        SrtStats: {
            connected?: boolean;
            rttMs?: number;
            packetLossPct?: number;
            bitrateKbps?: number;
        };
        /**
         * @description `youtube_http` = Route A (HTTP POST ingestion URL); `obs_websocket` = Route B (OBS SendStreamCaption, CEA-608)
         * @enum {string}
         */
        StreamCaptionTarget: "youtube_http" | "obs_websocket";
        StreamCaptionsConfig: {
            /** @default false */
            enabled: boolean;
            target?: components["schemas"]["StreamCaptionTarget"];
            /**
             * @description Caption track sent to the stream (a target language or `source`). YouTube supports one track.
             * @default en
             */
            track: string;
            /** @default 32 */
            maxCharsPerLine: number;
            /** @description Whether the ingestion URL secret is stored */
            readonly youtubeUrlSet?: boolean;
        };
        StreamCaptionStatus: {
            target?: components["schemas"]["StreamCaptionTarget"];
            /** @enum {string} */
            state: "disabled" | "idle" | "ok" | "retrying" | "error";
            /** Format: int64 */
            lastSeq?: number;
            lastSentAt?: components["schemas"]["Timestamp"];
            /** @description Local clock minus YouTube server clock */
            clockOffsetMs?: number;
            error?: components["schemas"]["Error"];
        };
        Caption: {
            sessionId: components["schemas"]["Slug"];
            /**
             * @description Track, a target language code, or `source`
             * @example es
             */
            lang: string;
            /** @example s-000123 */
            segmentId: string;
            /** @description false = interim text that will be replaced by a later event with the same segmentId (AI-6) */
            final: boolean;
            /** @example Hoy vamos a hablar de observabilidad en Kubernetes. */
            text: string;
            /**
             * @description Seconds from the session clock origin (= recording start) (REC-3)
             * @example 754.2
             */
            start: number;
            /** @example 757.9 */
            end: number;
            sourceLang: components["schemas"]["LanguageCode"];
            /** @example 1720 */
            latencyMs?: number;
            /** @default false */
            edited: boolean;
            /** @default false */
            hidden: boolean;
        };
        CaptionPage: {
            items: components["schemas"]["Caption"][];
            nextCursor?: string | null;
        };
        CaptionPatch: {
            text?: string;
            hidden?: boolean;
        };
        /** @description First client → server text frame on /ws/ingest */
        IngestHello: {
            /** @enum {string} */
            type: "hello";
            /** @enum {string} */
            format: "s16le";
            /** @enum {integer} */
            sampleRate: 16000;
            /** @enum {integer} */
            channels: 1;
            source?: components["schemas"]["AudioSourceKind"];
            deviceLabel?: string;
            /** @description Client epoch ms, for clock sync */
            clientTime?: number;
        };
        IngestServerMessage: {
            /** @enum {string} */
            type: "ready" | "level" | "state" | "error";
            state?: components["schemas"]["SessionState"];
            levelDbfs?: number;
            peakDbfs?: number;
            silent?: boolean;
            clipping?: boolean;
            error?: components["schemas"]["Error"];
        };
        /** @description Server → client text frame on /ws/captions */
        CaptionsServerMessage: {
            /** @enum {string} */
            type: "history" | "caption" | "state" | "viewers" | "error";
            /** @description Present when type=history */
            captions?: components["schemas"]["Caption"][];
            caption?: components["schemas"]["Caption"];
            state?: components["schemas"]["SessionState"];
            detectedLanguage?: components["schemas"]["LanguageCode"];
            viewers?: number;
            error?: components["schemas"]["Error"];
        };
        /** @description Server → client text frame on /ws/admin */
        AdminEvent: {
            /** @enum {string} */
            type: "sessionStatus" | "sessionCreated" | "sessionUpdated" | "sessionDeleted" | "modelProgress" | "streamCaptionStatus" | "log";
            at: components["schemas"]["Timestamp"];
            status?: components["schemas"]["SessionStatus"];
            session?: components["schemas"]["Session"];
            sessionId?: components["schemas"]["Slug"];
            model?: components["schemas"]["LocalModel"];
            log?: {
                /** @enum {string} */
                level: "info" | "warn" | "error";
                code: string;
                params?: {
                    [key: string]: unknown;
                };
                sessionId?: components["schemas"]["Slug"];
            };
        };
        Settings: {
            defaultSourceLanguage: components["schemas"]["SourceLanguage"];
            /**
             * @default [
             *       "es",
             *       "en"
             *     ]
             */
            defaultTargetLanguages: components["schemas"]["LanguageCode"][];
            defaultGlossaryId?: string | null;
            providers: {
                gemini: {
                    /** @description Gemini Live model id */
                    liveModel: string;
                    translationModel: string;
                };
                local: {
                    /** @default http://127.0.0.1:8178 */
                    whisperUrl: string;
                    /** @default large-v3-turbo */
                    whisperModel: string;
                    /** @default http://127.0.0.1:11434 */
                    ollamaUrl: string;
                    /** @default gemma3:4b */
                    gemmaModel: string;
                };
                /**
                 * @description Fall back to the other provider on failure (AI-8, stretch)
                 * @default false
                 */
                fallback: boolean;
            };
            translation?: {
                /** @default 3 */
                contextSentences: number;
            };
            captions?: {
                /** @default 42 */
                maxCharsPerLine: number;
                /** @default 2 */
                maxLines: number;
            };
            network: {
                /** @description Overrides the LAN URL in QR codes */
                publicBaseUrl?: string | null;
                preferredInterface?: string | null;
            };
            recording: {
                /** @default true */
                enabledByDefault: boolean;
                /**
                 * @default 32
                 * @enum {integer}
                 */
                bitrateKbps: 32 | 48 | 64;
                /**
                 * @description 0 = keep forever
                 * @default 30
                 */
                retentionDays: number;
            };
            /** @description Route B (CC-4); the password is stored as the `obs_websocket_password` secret */
            obs?: {
                /** @default ws://127.0.0.1:4455 */
                websocketUrl: string;
            };
            srt?: {
                /** @default true */
                enabled: boolean;
                /** @default 9000 */
                port: number;
                /** @default 200 */
                latencyMs: number;
                readonly passphraseSet?: boolean;
            };
        };
        ProvidersResponse: {
            defaultProvider: components["schemas"]["ProviderKind"];
            /** @enum {string} */
            defaultReason?: "google_api_key_valid" | "no_google_api_key" | "google_api_key_invalid";
            providers: components["schemas"]["ProviderInfo"][];
        };
        ProviderInfo: {
            kind: components["schemas"]["ProviderKind"];
            available: boolean;
            /** @description Why unavailable (translatable code) */
            reasonCode?: string;
            /** @description From the last benchmark (local only) */
            realtimeCapable?: boolean;
        };
        SecretInfo: {
            name: components["schemas"]["SecretName"];
            set: boolean;
            /** @description Last 4 chars, e.g. ••••abcd */
            hint?: string;
            /** @enum {string} */
            source?: "keychain" | "encrypted_file" | "env";
            updatedAt?: components["schemas"]["Timestamp"];
            /** @description Result of the last validation */
            valid?: boolean | null;
        };
        SecretWrite: {
            value: string;
            /** @default true */
            validate: boolean;
        };
        SecretValidation: {
            valid: boolean;
            /** @description Translatable reason when invalid */
            code?: string;
        };
        GlossaryInput: {
            name: string;
            terms: components["schemas"]["GlossaryTerm"][];
            /**
             * @example [
             *       "Kubernetes",
             *       "React",
             *       "Nerdearla"
             *     ]
             */
            doNotTranslate: string[];
        };
        Glossary: components["schemas"]["GlossaryInput"] & {
            id: string;
            updatedAt: components["schemas"]["Timestamp"];
        };
        GlossaryTerm: {
            /** @description Term as spoken/written in the source language */
            term: string;
            /** @description Preferred translation per language code */
            translations?: {
                [key: string]: string;
            };
            /** @description Context hint for the model */
            note?: string;
        };
        OverlayStyle: {
            /** @default Inter, system-ui, sans-serif */
            fontFamily: string;
            /** @default 44 */
            fontSizePx: number;
            /** @default 600 */
            fontWeight: number;
            /** @default #FFFFFF */
            color: string;
            /** @default #000000 */
            outlineColor: string;
            /** @default 3 */
            outlineWidthPx: number;
            /**
             * @description CSS color or `transparent`
             * @default rgba(0,0,0,0.55)
             */
            background: string;
            /**
             * @default bottom
             * @enum {string}
             */
            position: "bottom" | "top";
            /**
             * @default center
             * @enum {string}
             */
            align: "left" | "center" | "right";
            /** @default 60 */
            marginPx: number;
            /** @default 2 */
            maxLines: number;
            /**
             * @description Hide after silence; 0 = never
             * @default 6000
             */
            fadeAfterMs: number;
            /** @default true */
            showInterim: boolean;
        };
        OverlayPresetInput: {
            name: string;
            style: components["schemas"]["OverlayStyle"];
        };
        OverlayPreset: components["schemas"]["OverlayPresetInput"] & {
            id: string;
        };
        NetworkInfo: {
            hostname?: string;
            interfaces: {
                /** @example en0 */
                name: string;
                /** @example 192.168.1.20 */
                ip: string;
                /** @enum {string} */
                family: "ipv4" | "ipv6";
            }[];
            preferredIp?: string;
            /** @example 8080 */
            httpPort: number;
            /** @example 8443 */
            httpsPort?: number | null;
            /** @example 9000 */
            srtPort?: number | null;
            publicBaseUrl?: string | null;
            /**
             * @description publicBaseUrl if set, else http://<preferredIp>:<httpPort>
             * @example http://192.168.1.20:8080
             */
            viewerBaseUrl: string;
        };
        Recording: {
            id: string;
            sessionId: components["schemas"]["Slug"];
            title?: string;
            startedAt: components["schemas"]["Timestamp"];
            endedAt?: components["schemas"]["Timestamp"];
            durationSec?: number;
            /** Format: int64 */
            sizeBytes?: number;
            /** @enum {string} */
            status: "recording" | "complete" | "failed";
            languages: string[];
            expiresAt?: components["schemas"]["Timestamp"];
        };
        StorageUsage: {
            /** Format: int64 */
            usedBytes: number;
            /** Format: int64 */
            freeBytes?: number;
            recordings: number;
        };
        ReprocessRequest: {
            provider?: components["schemas"]["ProviderKind"];
            glossaryId?: string;
            targetLanguages?: components["schemas"]["LanguageCode"][];
        };
        Job: {
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed";
            progress?: number;
            error?: components["schemas"]["Error"];
        };
        LocalModel: {
            /** @example whisper-large-v3-turbo */
            id: string;
            /** @enum {string} */
            kind: "whisper" | "gemma";
            name: string;
            /** Format: int64 */
            sizeBytes?: number;
            recommended?: boolean;
            /** @enum {string} */
            status: "missing" | "downloading" | "verifying" | "ready" | "error";
            progress?: number;
            error?: components["schemas"]["Error"];
        };
        TlsInfo: {
            enabled: boolean;
            /** @enum {string} */
            mode: "local-ca" | "provided" | "acme" | "disabled";
            httpsPort?: number;
            sans?: string[];
            notAfter?: components["schemas"]["Timestamp"];
            caFingerprintSha256?: string;
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Valid request that cannot be fulfilled (e.g. provider unavailable) */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Session slug (URL-safe, e.g. `main-stage`) */
        SessionId: components["schemas"]["Slug"];
        RecordingId: string;
        SecretName: components["schemas"]["SecretName"];
        /** @description Caption track, a target language code or `source` */
        LangQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    getHardwareReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    runBenchmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Benchmark finished */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Setup completed; an admin session cookie is set */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; admin session cookie set */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current auth state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Created. The ingest token is only returned here and on rotation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionWithToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionStartRequest"];
            };
        };
        responses: {
            /** @description Starting / live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    pauseSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    stopSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    rotateIngestToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startFileSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileSourceRequest"];
            };
        };
        responses: {
            /** @description Source started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    stopFileSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source stopped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putYoutubeCaptionUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretWrite"];
            };
        };
        responses: {
            /** @description Stored; only masked info is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteYoutubeCaptionUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendTestStreamCaption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    text?: string;
                };
            };
        };
        responses: {
            /** @description Delivery result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamCaptionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listPublicSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSession"][];
                };
            };
        };
    };
    getPublicSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSession"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCaptions: {
        parameters: {
            query: {
                /** @description Caption track, a target language code or `source` */
                lang: components["parameters"]["LangQuery"];
                /** @description Opaque cursor from a previous page */
                after?: string;
                limit?: number;
                /** @description Restrict to captions belonging to one recording (timestamps relative to it) */
                recordingId?: string;
            };
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptionPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSubtitles: {
        parameters: {
            query: {
                /** @description Caption track, a target language code or `source` */
                lang: components["parameters"]["LangQuery"];
                format: components["schemas"]["SubtitleFormat"];
                live?: boolean;
                recordingId?: string;
            };
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subtitle file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/vtt": string;
                    "application/x-subrip": string;
                    "text/plain": string;
                    "application/json": components["schemas"]["Caption"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    patchCaption: {
        parameters: {
            query: {
                /** @description Caption track, a target language code or `source` */
                lang: components["parameters"]["LangQuery"];
            };
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptionPatch"];
            };
        };
        responses: {
            /** @description Updated; a `caption` event with `edited=true` is broadcast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Caption"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    wsIngest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    wsCaptions: {
        parameters: {
            query: {
                lang: string[];
                /** @description Number of recent final captions to send on connect */
                history?: number;
            };
            header?: never;
            path: {
                /** @description Session slug (URL-safe, e.g. `main-stage`) */
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    wsAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretWrite"];
            };
        };
        responses: {
            /** @description Stored (masked info only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    validateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretValidation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGlossaries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGlossary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getGlossary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glossaryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGlossary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glossaryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteGlossary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glossaryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOverlayPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayPreset"][];
                };
            };
        };
    };
    createOverlayPreset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayPresetInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayPreset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getOverlayPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayPreset"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateOverlayPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayPresetInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayPreset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteOverlayPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getNetworkInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkInfo"];
                };
            };
        };
    };
    listRecordings: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"][];
                };
            };
        };
    };
    getRecordingUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUsage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRecordingAudio: {
        parameters: {
            query?: never;
            header?: {
                Range?: string;
            };
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mp4": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mp4": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reprocessRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReprocessRequest"];
            };
        };
        responses: {
            /** @description Job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalModel"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    downloadModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalModel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getTlsInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TlsInfo"];
                };
            };
        };
    };
    downloadCaCert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PEM certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-x509-ca-cert": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
