// Code generated by scripts/gen-unimplemented.py. DO NOT EDIT.

package api

import (
	"context"
	"errors"
)

// ErrNotImplemented is returned by operations that have no handler yet.
var ErrNotImplemented = errors.New("not implemented")

// Unimplemented answers every operation with ErrNotImplemented. Embed it in
// the server type and override the operations you implement.
type Unimplemented struct{}

var _ StrictServerInterface = Unimplemented{}

func (Unimplemented) Login(context.Context, LoginRequestObject) (LoginResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) Logout(context.Context, LogoutRequestObject) (LogoutResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetMe(context.Context, GetMeRequestObject) (GetMeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListGlossaries(context.Context, ListGlossariesRequestObject) (ListGlossariesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateGlossary(context.Context, CreateGlossaryRequestObject) (CreateGlossaryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DeleteGlossary(context.Context, DeleteGlossaryRequestObject) (DeleteGlossaryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetGlossary(context.Context, GetGlossaryRequestObject) (GetGlossaryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateGlossary(context.Context, UpdateGlossaryRequestObject) (UpdateGlossaryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListLanguages(context.Context, ListLanguagesRequestObject) (ListLanguagesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListModels(context.Context, ListModelsRequestObject) (ListModelsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DownloadModel(context.Context, DownloadModelRequestObject) (DownloadModelResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetNetworkInfo(context.Context, GetNetworkInfoRequestObject) (GetNetworkInfoResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListOverlayPresets(context.Context, ListOverlayPresetsRequestObject) (ListOverlayPresetsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateOverlayPreset(context.Context, CreateOverlayPresetRequestObject) (CreateOverlayPresetResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DeleteOverlayPreset(context.Context, DeleteOverlayPresetRequestObject) (DeleteOverlayPresetResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetOverlayPreset(context.Context, GetOverlayPresetRequestObject) (GetOverlayPresetResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateOverlayPreset(context.Context, UpdateOverlayPresetRequestObject) (UpdateOverlayPresetResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListProviders(context.Context, ListProvidersRequestObject) (ListProvidersResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListPublicSessions(context.Context, ListPublicSessionsRequestObject) (ListPublicSessionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetPublicSession(context.Context, GetPublicSessionRequestObject) (GetPublicSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListCaptions(context.Context, ListCaptionsRequestObject) (ListCaptionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetSubtitles(context.Context, GetSubtitlesRequestObject) (GetSubtitlesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListRecordings(context.Context, ListRecordingsRequestObject) (ListRecordingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetRecordingUsage(context.Context, GetRecordingUsageRequestObject) (GetRecordingUsageResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DeleteRecording(context.Context, DeleteRecordingRequestObject) (DeleteRecordingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetRecording(context.Context, GetRecordingRequestObject) (GetRecordingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetRecordingAudio(context.Context, GetRecordingAudioRequestObject) (GetRecordingAudioResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ReprocessRecording(context.Context, ReprocessRecordingRequestObject) (ReprocessRecordingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListSecrets(context.Context, ListSecretsRequestObject) (ListSecretsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DeleteSecret(context.Context, DeleteSecretRequestObject) (DeleteSecretResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) PutSecret(context.Context, PutSecretRequestObject) (PutSecretResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ValidateSecret(context.Context, ValidateSecretRequestObject) (ValidateSecretResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) ListSessions(context.Context, ListSessionsRequestObject) (ListSessionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CreateSession(context.Context, CreateSessionRequestObject) (CreateSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DeleteSession(context.Context, DeleteSessionRequestObject) (DeleteSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetSession(context.Context, GetSessionRequestObject) (GetSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateSession(context.Context, UpdateSessionRequestObject) (UpdateSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) PatchCaption(context.Context, PatchCaptionRequestObject) (PatchCaptionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) RotateIngestToken(context.Context, RotateIngestTokenRequestObject) (RotateIngestTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) PauseSession(context.Context, PauseSessionRequestObject) (PauseSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) StopFileSource(context.Context, StopFileSourceRequestObject) (StopFileSourceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) StartFileSource(context.Context, StartFileSourceRequestObject) (StartFileSourceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) StartSession(context.Context, StartSessionRequestObject) (StartSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetSessionStatus(context.Context, GetSessionStatusRequestObject) (GetSessionStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) StopSession(context.Context, StopSessionRequestObject) (StopSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) SendTestStreamCaption(context.Context, SendTestStreamCaptionRequestObject) (SendTestStreamCaptionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DeleteYoutubeCaptionUrl(context.Context, DeleteYoutubeCaptionUrlRequestObject) (DeleteYoutubeCaptionUrlResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) PutYoutubeCaptionUrl(context.Context, PutYoutubeCaptionUrlRequestObject) (PutYoutubeCaptionUrlResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetSettings(context.Context, GetSettingsRequestObject) (GetSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) UpdateSettings(context.Context, UpdateSettingsRequestObject) (UpdateSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetSetupStatus(context.Context, GetSetupStatusRequestObject) (GetSetupStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) CompleteSetup(context.Context, CompleteSetupRequestObject) (CompleteSetupResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) RunBenchmark(context.Context, RunBenchmarkRequestObject) (RunBenchmarkResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetHardwareReport(context.Context, GetHardwareReportRequestObject) (GetHardwareReportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetSystemInfo(context.Context, GetSystemInfoRequestObject) (GetSystemInfoResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetTlsInfo(context.Context, GetTlsInfoRequestObject) (GetTlsInfoResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) DownloadCaCert(context.Context, DownloadCaCertRequestObject) (DownloadCaCertResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) GetHealth(context.Context, GetHealthRequestObject) (GetHealthResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) WsAdmin(context.Context, WsAdminRequestObject) (WsAdminResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) WsCaptions(context.Context, WsCaptionsRequestObject) (WsCaptionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (Unimplemented) WsIngest(context.Context, WsIngestRequestObject) (WsIngestResponseObject, error) {
	return nil, ErrNotImplemented
}
