#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate web/src/theme/palette.ts (sRGB hex) from web/src/theme/tokens.css (OKLCH).

MUI's colour utilities (alpha, darken, contrast text) don't parse oklch(), so the
MUI palette is fed hex values mirrored from the canonical OKLCH tokens.
Run: python3 scripts/gen-palette.py
"""
from tokens import ROOT, TOKENS as SRC, oklch_to_hex, schemes

OUT = ROOT / "web/src/theme/palette.ts"

def colours(tokens):
    return {k[len("color-"):]: oklch_to_hex(*v) for k, v in tokens.items() if k.startswith("color-")}

light, dark = map(colours, schemes())

def camel(k):
    p = k.split("-"); return p[0] + "".join(x.title() for x in p[1:])

def obj(d):
    return "\n".join(f"  {camel(k)}: '{v}'," for k, v in d.items())

OUT.write_text(f"""// SPDX-License-Identifier: Apache-2.0
// GENERATED by scripts/gen-palette.py from tokens.css. Do not edit by hand.
// sRGB mirrors of the OKLCH tokens, for MUI's palette (it can't parse oklch()).

export const light = {{
{obj(light)}
}} as const;

export const dark = {{
{obj(dark)}
}} as const;

export type Palette = typeof light;
""")
print(f"wrote {OUT.relative_to(ROOT)}: {len(light)} light / {len(dark)} dark colours")
