#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate internal/api/unimplemented_gen.go from internal/api/gen.go.

Writes an Unimplemented type whose methods satisfy StrictServerInterface by
returning ErrNotImplemented. Handlers embed it and override the operations
they implement, so every operation in the spec is routed from day one.
Run: python3 scripts/gen-unimplemented.py (part of `task gen`)
"""
import pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "internal/api/gen.go"
OUT = ROOT / "internal/api/unimplemented_gen.go"

src = SRC.read_text()
block = re.search(r"^type StrictServerInterface interface \{\n(.*?)^\}", src, re.S | re.M)
if not block:
    sys.exit("StrictServerInterface not found in " + str(SRC))
methods = re.findall(
    r"^\t(\w+)\(ctx context\.Context, request (\w+)\) \((\w+), error\)$", block.group(1), re.M)
if not methods:
    sys.exit("no methods found in StrictServerInterface")

out = ['''// Code generated by scripts/gen-unimplemented.py. DO NOT EDIT.

package api

import (
\t"context"
\t"errors"
)

// ErrNotImplemented is returned by operations that have no handler yet.
var ErrNotImplemented = errors.New("not implemented")

// Unimplemented answers every operation with ErrNotImplemented. Embed it in
// the server type and override the operations you implement.
type Unimplemented struct{}

var _ StrictServerInterface = Unimplemented{}
''']
for name, req, resp in methods:
    out.append(f'''
func (Unimplemented) {name}(context.Context, {req}) ({resp}, error) {{
\treturn nil, ErrNotImplemented
}}
''')
OUT.write_text("".join(out))
subprocess.run(["gofmt", "-w", str(OUT)], check=True)
print(f"wrote {OUT.relative_to(ROOT)}: {len(methods)} operations")
