/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemedRouteImport } from './routes/_themed'
import { Route as ThemedIndexRouteImport } from './routes/_themed/index'
import { Route as ThemedAdminRouteRouteImport } from './routes/_themed/admin/route'
import { Route as ThemedSetupRouteImport } from './routes/_themed/setup'
import { Route as OverlayIdRouteImport } from './routes/overlay/$id'
import { Route as StageIdRouteImport } from './routes/stage/$id'
import { Route as ThemedAdminIndexRouteImport } from './routes/_themed/admin/index'
import { Route as ThemedAdminGlossariesRouteImport } from './routes/_themed/admin/glossaries'
import { Route as ThemedAdminOverlaysRouteImport } from './routes/_themed/admin/overlays'
import { Route as ThemedAdminProvidersRouteImport } from './routes/_themed/admin/providers'
import { Route as ThemedAdminSettingsRouteImport } from './routes/_themed/admin/settings'
import { Route as ThemedAdminTlsRouteImport } from './routes/_themed/admin/tls'
import { Route as ThemedCaptureIdRouteImport } from './routes/_themed/capture/$id'
import { Route as ThemedDevDesignRouteImport } from './routes/_themed/dev/design'
import { Route as ThemedReplayIdRouteImport } from './routes/_themed/replay/$id'
import { Route as ThemedSIndexRouteImport } from './routes/_themed/s/index'
import { Route as ThemedSIdRouteImport } from './routes/_themed/s/$id'

const ThemedRoute = ThemedRouteImport.update({
  id: '/_themed',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemedIndexRoute = ThemedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemedRoute,
} as any)
const ThemedAdminRouteRoute = ThemedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ThemedRoute,
} as any)
const ThemedSetupRoute = ThemedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ThemedRoute,
} as any)
const OverlayIdRoute = OverlayIdRouteImport.update({
  id: '/overlay/$id',
  path: '/overlay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StageIdRoute = StageIdRouteImport.update({
  id: '/stage/$id',
  path: '/stage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemedAdminIndexRoute = ThemedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemedAdminRouteRoute,
} as any)
const ThemedAdminGlossariesRoute = ThemedAdminGlossariesRouteImport.update({
  id: '/glossaries',
  path: '/glossaries',
  getParentRoute: () => ThemedAdminRouteRoute,
} as any)
const ThemedAdminOverlaysRoute = ThemedAdminOverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => ThemedAdminRouteRoute,
} as any)
const ThemedAdminProvidersRoute = ThemedAdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ThemedAdminRouteRoute,
} as any)
const ThemedAdminSettingsRoute = ThemedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ThemedAdminRouteRoute,
} as any)
const ThemedAdminTlsRoute = ThemedAdminTlsRouteImport.update({
  id: '/tls',
  path: '/tls',
  getParentRoute: () => ThemedAdminRouteRoute,
} as any)
const ThemedCaptureIdRoute = ThemedCaptureIdRouteImport.update({
  id: '/capture/$id',
  path: '/capture/$id',
  getParentRoute: () => ThemedRoute,
} as any)
const ThemedDevDesignRoute = ThemedDevDesignRouteImport.update({
  id: '/dev/design',
  path: '/dev/design',
  getParentRoute: () => ThemedRoute,
} as any)
const ThemedReplayIdRoute = ThemedReplayIdRouteImport.update({
  id: '/replay/$id',
  path: '/replay/$id',
  getParentRoute: () => ThemedRoute,
} as any)
const ThemedSIndexRoute = ThemedSIndexRouteImport.update({
  id: '/s/',
  path: '/s/',
  getParentRoute: () => ThemedRoute,
} as any)
const ThemedSIdRoute = ThemedSIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => ThemedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ThemedIndexRoute
  '/admin': typeof ThemedAdminRouteRouteWithChildren
  '/setup': typeof ThemedSetupRoute
  '/overlay/$id': typeof OverlayIdRoute
  '/stage/$id': typeof StageIdRoute
  '/admin/glossaries': typeof ThemedAdminGlossariesRoute
  '/admin/overlays': typeof ThemedAdminOverlaysRoute
  '/admin/providers': typeof ThemedAdminProvidersRoute
  '/admin/settings': typeof ThemedAdminSettingsRoute
  '/admin/tls': typeof ThemedAdminTlsRoute
  '/capture/$id': typeof ThemedCaptureIdRoute
  '/dev/design': typeof ThemedDevDesignRoute
  '/replay/$id': typeof ThemedReplayIdRoute
  '/s/$id': typeof ThemedSIdRoute
  '/admin/': typeof ThemedAdminIndexRoute
  '/s/': typeof ThemedSIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof ThemedSetupRoute
  '/overlay/$id': typeof OverlayIdRoute
  '/stage/$id': typeof StageIdRoute
  '/': typeof ThemedIndexRoute
  '/admin/glossaries': typeof ThemedAdminGlossariesRoute
  '/admin/overlays': typeof ThemedAdminOverlaysRoute
  '/admin/providers': typeof ThemedAdminProvidersRoute
  '/admin/settings': typeof ThemedAdminSettingsRoute
  '/admin/tls': typeof ThemedAdminTlsRoute
  '/capture/$id': typeof ThemedCaptureIdRoute
  '/dev/design': typeof ThemedDevDesignRoute
  '/replay/$id': typeof ThemedReplayIdRoute
  '/s/$id': typeof ThemedSIdRoute
  '/admin': typeof ThemedAdminIndexRoute
  '/s': typeof ThemedSIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_themed': typeof ThemedRouteWithChildren
  '/_themed/admin': typeof ThemedAdminRouteRouteWithChildren
  '/_themed/setup': typeof ThemedSetupRoute
  '/overlay/$id': typeof OverlayIdRoute
  '/stage/$id': typeof StageIdRoute
  '/_themed/': typeof ThemedIndexRoute
  '/_themed/admin/glossaries': typeof ThemedAdminGlossariesRoute
  '/_themed/admin/overlays': typeof ThemedAdminOverlaysRoute
  '/_themed/admin/providers': typeof ThemedAdminProvidersRoute
  '/_themed/admin/settings': typeof ThemedAdminSettingsRoute
  '/_themed/admin/tls': typeof ThemedAdminTlsRoute
  '/_themed/capture/$id': typeof ThemedCaptureIdRoute
  '/_themed/dev/design': typeof ThemedDevDesignRoute
  '/_themed/replay/$id': typeof ThemedReplayIdRoute
  '/_themed/s/$id': typeof ThemedSIdRoute
  '/_themed/admin/': typeof ThemedAdminIndexRoute
  '/_themed/s/': typeof ThemedSIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/setup'
    | '/overlay/$id'
    | '/stage/$id'
    | '/admin/glossaries'
    | '/admin/overlays'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/tls'
    | '/capture/$id'
    | '/dev/design'
    | '/replay/$id'
    | '/s/$id'
    | '/admin/'
    | '/s/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/overlay/$id'
    | '/stage/$id'
    | '/'
    | '/admin/glossaries'
    | '/admin/overlays'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/tls'
    | '/capture/$id'
    | '/dev/design'
    | '/replay/$id'
    | '/s/$id'
    | '/admin'
    | '/s'
  id:
    | '__root__'
    | '/_themed'
    | '/_themed/admin'
    | '/_themed/setup'
    | '/overlay/$id'
    | '/stage/$id'
    | '/_themed/'
    | '/_themed/admin/glossaries'
    | '/_themed/admin/overlays'
    | '/_themed/admin/providers'
    | '/_themed/admin/settings'
    | '/_themed/admin/tls'
    | '/_themed/capture/$id'
    | '/_themed/dev/design'
    | '/_themed/replay/$id'
    | '/_themed/s/$id'
    | '/_themed/admin/'
    | '/_themed/s/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ThemedRoute: typeof ThemedRouteWithChildren
  OverlayIdRoute: typeof OverlayIdRoute
  StageIdRoute: typeof StageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_themed': {
      id: '/_themed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ThemedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_themed/': {
      id: '/_themed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ThemedIndexRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/_themed/admin': {
      id: '/_themed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ThemedAdminRouteRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/_themed/setup': {
      id: '/_themed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof ThemedSetupRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/overlay/$id': {
      id: '/overlay/$id'
      path: '/overlay/$id'
      fullPath: '/overlay/$id'
      preLoaderRoute: typeof OverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$id': {
      id: '/stage/$id'
      path: '/stage/$id'
      fullPath: '/stage/$id'
      preLoaderRoute: typeof StageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_themed/admin/': {
      id: '/_themed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ThemedAdminIndexRouteImport
      parentRoute: typeof ThemedAdminRouteRoute
    }
    '/_themed/admin/glossaries': {
      id: '/_themed/admin/glossaries'
      path: '/glossaries'
      fullPath: '/admin/glossaries'
      preLoaderRoute: typeof ThemedAdminGlossariesRouteImport
      parentRoute: typeof ThemedAdminRouteRoute
    }
    '/_themed/admin/overlays': {
      id: '/_themed/admin/overlays'
      path: '/overlays'
      fullPath: '/admin/overlays'
      preLoaderRoute: typeof ThemedAdminOverlaysRouteImport
      parentRoute: typeof ThemedAdminRouteRoute
    }
    '/_themed/admin/providers': {
      id: '/_themed/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof ThemedAdminProvidersRouteImport
      parentRoute: typeof ThemedAdminRouteRoute
    }
    '/_themed/admin/settings': {
      id: '/_themed/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof ThemedAdminSettingsRouteImport
      parentRoute: typeof ThemedAdminRouteRoute
    }
    '/_themed/admin/tls': {
      id: '/_themed/admin/tls'
      path: '/tls'
      fullPath: '/admin/tls'
      preLoaderRoute: typeof ThemedAdminTlsRouteImport
      parentRoute: typeof ThemedAdminRouteRoute
    }
    '/_themed/capture/$id': {
      id: '/_themed/capture/$id'
      path: '/capture/$id'
      fullPath: '/capture/$id'
      preLoaderRoute: typeof ThemedCaptureIdRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/_themed/dev/design': {
      id: '/_themed/dev/design'
      path: '/dev/design'
      fullPath: '/dev/design'
      preLoaderRoute: typeof ThemedDevDesignRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/_themed/replay/$id': {
      id: '/_themed/replay/$id'
      path: '/replay/$id'
      fullPath: '/replay/$id'
      preLoaderRoute: typeof ThemedReplayIdRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/_themed/s/': {
      id: '/_themed/s/'
      path: '/s'
      fullPath: '/s/'
      preLoaderRoute: typeof ThemedSIndexRouteImport
      parentRoute: typeof ThemedRoute
    }
    '/_themed/s/$id': {
      id: '/_themed/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof ThemedSIdRouteImport
      parentRoute: typeof ThemedRoute
    }
  }
}

interface ThemedAdminRouteRouteChildren {
  ThemedAdminGlossariesRoute: typeof ThemedAdminGlossariesRoute
  ThemedAdminOverlaysRoute: typeof ThemedAdminOverlaysRoute
  ThemedAdminProvidersRoute: typeof ThemedAdminProvidersRoute
  ThemedAdminSettingsRoute: typeof ThemedAdminSettingsRoute
  ThemedAdminTlsRoute: typeof ThemedAdminTlsRoute
  ThemedAdminIndexRoute: typeof ThemedAdminIndexRoute
}

const ThemedAdminRouteRouteChildren: ThemedAdminRouteRouteChildren = {
  ThemedAdminGlossariesRoute: ThemedAdminGlossariesRoute,
  ThemedAdminOverlaysRoute: ThemedAdminOverlaysRoute,
  ThemedAdminProvidersRoute: ThemedAdminProvidersRoute,
  ThemedAdminSettingsRoute: ThemedAdminSettingsRoute,
  ThemedAdminTlsRoute: ThemedAdminTlsRoute,
  ThemedAdminIndexRoute: ThemedAdminIndexRoute,
}

const ThemedAdminRouteRouteWithChildren =
  ThemedAdminRouteRoute._addFileChildren(ThemedAdminRouteRouteChildren)

interface ThemedRouteChildren {
  ThemedAdminRouteRoute: typeof ThemedAdminRouteRouteWithChildren
  ThemedSetupRoute: typeof ThemedSetupRoute
  ThemedIndexRoute: typeof ThemedIndexRoute
  ThemedCaptureIdRoute: typeof ThemedCaptureIdRoute
  ThemedDevDesignRoute: typeof ThemedDevDesignRoute
  ThemedReplayIdRoute: typeof ThemedReplayIdRoute
  ThemedSIdRoute: typeof ThemedSIdRoute
  ThemedSIndexRoute: typeof ThemedSIndexRoute
}

const ThemedRouteChildren: ThemedRouteChildren = {
  ThemedAdminRouteRoute: ThemedAdminRouteRouteWithChildren,
  ThemedSetupRoute: ThemedSetupRoute,
  ThemedIndexRoute: ThemedIndexRoute,
  ThemedCaptureIdRoute: ThemedCaptureIdRoute,
  ThemedDevDesignRoute: ThemedDevDesignRoute,
  ThemedReplayIdRoute: ThemedReplayIdRoute,
  ThemedSIdRoute: ThemedSIdRoute,
  ThemedSIndexRoute: ThemedSIndexRoute,
}

const ThemedRouteWithChildren =
  ThemedRoute._addFileChildren(ThemedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ThemedRoute: ThemedRouteWithChildren,
  OverlayIdRoute: OverlayIdRoute,
  StageIdRoute: StageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
